# Generated by Django 5.0.7 on 2024-08-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("synopsis", models.TextField(verbose_name="Synopsis")),
                (
                    "img",
                    models.ImageField(upload_to="image/%Y/%m", verbose_name="Image"),
                ),
                ("started_airing", models.DateField(verbose_name="Started airing")),
                ("finished_airing", models.DateField(verbose_name="Finished airing")),
                ("publish_date", models.DateField(verbose_name="Publish date")),
            ],
            options={
                "verbose_name": "Anime",
                "verbose_name_plural": "Animes",
            },
        ),
    ]
