# Generated by Django 5.0.7 on 2024-08-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("amscore", "0002_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="email",
        ),
    ]
